# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCc5Ve0OyO3GFKZKE3OHu_moo-zCrkLQ
"""

import os
import traceback
import pypdf
import gradio as gr
from pathlib import Path
from huggingface_hub import InferenceClient, login

# ─── Authentication ───────────────────────────────────────────────────────────
HF_TOKEN = os.environ.get('HF_TOKEN')
if not HF_TOKEN:
    raise EnvironmentError("HF_TOKEN secret is missing! Go to Space Settings → Secrets → New Secret")
login(token=HF_TOKEN)

# ─── Config ───────────────────────────────────────────────────────────────────
PDF_FILENAME      = 'scikit-learn-cheat-sheet.pdf'   # ← change to your PDF filename
MAX_CONTEXT_CHARS = 6_000

# ─── Models ───────────────────────────────────────────────────────────────────
AVAILABLE_MODELS = {
    'Llama 3.1 — 3B Instruct': 'meta-llama/Llama-3.1-8B-Instruct',
}
DEFAULT_MODEL = 'Llama 3.1 — 3B Instruct'

# ─── PDF Loading ──────────────────────────────────────────────────────────────
def extract_text(path: str) -> str:
    reader = pypdf.PdfReader(path)
    return '\n'.join(p.extract_text() for p in reader.pages if p.extract_text())

try:
    FIXED_PDF_TEXT = extract_text(PDF_FILENAME)
    print(f'Fixed PDF loaded: {len(FIXED_PDF_TEXT):,} characters')
except FileNotFoundError:
    FIXED_PDF_TEXT = ''
    print('No fixed PDF found — upload mode will still work.')

# ─── Model Client ─────────────────────────────────────────────────────────────
current_client   = None
current_model_id = None

def load_model(display_name: str) -> str:
    global current_client, current_model_id
    model_id = AVAILABLE_MODELS.get(display_name)
    if not model_id:
        return f'❌ Unknown model: {display_name}'
    if model_id == current_model_id and current_client is not None:
        return f'✅ {display_name} is already active.'
    try:
        current_client   = InferenceClient(model_id, token=HF_TOKEN)
        current_model_id = model_id
        return f'✅ {display_name} ready!'
    except Exception as e:
        current_client   = None
        current_model_id = None
        return f'❌ Error: {e}'

print(load_model(DEFAULT_MODEL))

# ─── Q&A Function ─────────────────────────────────────────────────────────────
def answer_question(question: str, use_upload: bool, uploaded_text: str) -> str:
    if not current_client:
        return '⚠️ No model loaded. Please click Load Model.'
    if not question.strip():
        return '⚠️ Please enter a question.'

    context = (uploaded_text or '').strip() if use_upload else FIXED_PDF_TEXT[:MAX_CONTEXT_CHARS]
    if not context:
        return '⚠️ No document loaded. Please upload a PDF or check the fixed document.'

    system_msg = (
        'You are a helpful assistant. '
        'Answer the question based ONLY on the provided document. '
        'If the answer is not in the document, say: '
        'The document does not contain information on this topic.'
    )

    try:
        response = current_client.chat_completion(
            messages=[
                {"role": "system", "content": f"{system_msg}\n\nDocument:\n{context}"},
                {"role": "user",   "content": question},
            ],
            max_tokens=500,
            temperature=0.2,
        )
        answer = response.choices[0].message.content
        return answer.strip() if answer else "(No answer generated)"
    except Exception as e:
        print(traceback.format_exc())
        return f'❌ Error: {type(e).__name__}: {str(e)}'

# ─── Gradio UI ────────────────────────────────────────────────────────────────
TERMS = """
### ⚠️ Terms of Use
By using this app you agree that:
- This tool is for **educational and informational purposes only**
- You will not upload illegal or harmful content
- Answers are AI-generated — always verify important information
"""

def process_upload(pdf_file):
    if pdf_file is None:
        return '', 'No file uploaded.'
    try:
        text = extract_text(pdf_file.name)
        count = len(text)
        if count == 0:
            return '', '❌ Could not extract text from this PDF.'
        warning = f' ⚠️ Trimmed to {MAX_CONTEXT_CHARS:,} chars.' if count > MAX_CONTEXT_CHARS else ''
        return text[:MAX_CONTEXT_CHARS], f'✅ {count:,} characters loaded.{warning}'
    except Exception as e:
        return '', f'❌ Error: {e}'

def route_answer(question, model_name, pdf_source, uploaded_text):
    use_upload = (pdf_source == 'Upload my own PDF')
    return answer_question(question, use_upload, uploaded_text or '')

with gr.Blocks(theme=gr.themes.Soft(), title='PDF Q&A Bot') as demo:

    gr.Markdown(
        '# 📄 PDF Q&A Bot\n'
        'Ask questions about a PDF using open-source AI.\n\n'
        '> Powered by HuggingFace Inference API'
    )
    gr.Markdown(TERMS)

    with gr.Row():
        model_dd = gr.Dropdown(
            choices=list(AVAILABLE_MODELS.keys()),
            value=DEFAULT_MODEL,
            label='🤖 Select Model',
            scale=2,
        )
        load_btn = gr.Button('Load Model', variant='secondary', scale=1)

    model_status = gr.Textbox(
        label='Model Status',
        value=f'✅ {DEFAULT_MODEL} ready!',
        interactive=False,
    )

    gr.Markdown('---')

    pdf_source = gr.Radio(
        choices=['Use fixed document', 'Upload my own PDF'],
        value='Use fixed document',
        label='📂 Document Source',
    )

    fixed_info = gr.Markdown(
        f'📄 **Fixed document:** `{PDF_FILENAME}` — {len(FIXED_PDF_TEXT):,} characters'
        if FIXED_PDF_TEXT else '⚠️ No fixed document found on server.'
    )

    with gr.Column(visible=False) as upload_col:
        pdf_upload = gr.File(label='Upload PDF', file_types=['.pdf'])
        gr.Markdown(
            '> 💡 **Hint:** Keep your PDF under **6,000 characters** (~4–5 pages). '
            'Larger files will be trimmed automatically.'
        )
        upload_status = gr.Textbox(label='Upload Status', interactive=False)

    uploaded_text_state = gr.State('')

    gr.Markdown('---')

    question_box = gr.Textbox(
        label='❓ Your Question',
        placeholder='e.g. What is the main topic of this document?',
        lines=2,
    )
    ask_btn    = gr.Button('Ask', variant='primary')
    answer_box = gr.Textbox(label='💡 Answer', lines=6, interactive=False)

    gr.Markdown('---\n*Answers are AI-generated. Do not rely on them for critical decisions.*')

    # ── Events ──
    load_btn.click(fn=load_model, inputs=[model_dd], outputs=[model_status])

    pdf_source.change(
        fn=lambda c: (gr.update(visible=c == 'Upload my own PDF'), gr.update(visible=c == 'Use fixed document')),
        inputs=[pdf_source],
        outputs=[upload_col, fixed_info],
    )
    pdf_upload.change(
        fn=process_upload,
        inputs=[pdf_upload],
        outputs=[uploaded_text_state, upload_status],
    )
    ask_btn.click(
        fn=route_answer,
        inputs=[question_box, model_dd, pdf_source, uploaded_text_state],
        outputs=[answer_box],
    )
    question_box.submit(
        fn=route_answer,
        inputs=[question_box, model_dd, pdf_source, uploaded_text_state],
        outputs=[answer_box],
    )

demo.launch()